// <auto-generated />
namespace Attendance.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changing_data_type_Alternative : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changing_data_type_Alternative));
        
        string IMigrationMetadata.Id
        {
            get { return "201810011103363_changing_data_type_Alternative"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
