// <auto-generated />
namespace Attendance.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedField_IsMobileAppEligible_In_StaffOfficial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedField_IsMobileAppEligible_In_StaffOfficial));
        
        string IMigrationMetadata.Id
        {
            get { return "202008110700432_AddedField_IsMobileAppEligible_In_StaffOfficial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
