// <auto-generated />
namespace Attendance.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcolumnManualShiftinStaffOfficialtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcolumnManualShiftinStaffOfficialtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201904010634112_addcolumnManualShiftinStaffOfficialtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
