namespace Attendance.Repository.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddedRangeStaffIdfromAllTable : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.StaffEducation", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.StaffFamily", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.AbsenceApproval", "ApprovedById", "dbo.Staff");
            DropForeignKey("dbo.LeaveApplication", "CreatedBy", "dbo.Staff");
            DropForeignKey("dbo.LeaveApplication", "ModifiedBy", "dbo.Staff");
            DropForeignKey("dbo.LeaveApplication", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.ApplicationEntry", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.AttendanceData", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.CompensatoryOff", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.EmployeeGroupTxn", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.EmployeeLeaveAccount", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.GroupAssociation", "EmployeeId", "dbo.Staff");
            DropForeignKey("dbo.LaterOff", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.MaintenanceOff", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.ManualPunch", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.OTApplication", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.OTApplicationEntry", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.PermissionOff", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.PermissionTxn", "ApprovalStatusBy", "dbo.Staff");
            DropForeignKey("dbo.PermissionTxn", "CreatedBy", "dbo.Staff");
            DropForeignKey("dbo.PermissionTxn", "ModifiedBy", "dbo.Staff");
            DropForeignKey("dbo.PermissionTxn", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.RHApplication", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.StaffOfficial", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.StaffPersonal", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.SwipeData", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.TeamHierarchy", "ReportingManagerId", "dbo.Staff");
            DropForeignKey("dbo.TeamHierarchy", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.ViewApproval", "ApproverID", "dbo.Staff");
            DropIndex("dbo.AbsenceApproval", new[] { "ApprovedById" });
            DropIndex("dbo.StaffEducation", new[] { "StaffId" });
            DropIndex("dbo.StaffFamily", new[] { "StaffId" });
            DropIndex("dbo.LeaveApplication", new[] { "StaffId" });
            DropIndex("dbo.LeaveApplication", new[] { "CreatedBy" });
            DropIndex("dbo.LeaveApplication", new[] { "ModifiedBy" });
            DropIndex("dbo.ApplicationEntry", new[] { "StaffId" });
            DropIndex("dbo.AttendanceData", new[] { "StaffId" });
            DropIndex("dbo.CompensatoryOff", new[] { "StaffId" });
            DropIndex("dbo.EmployeeGroupTxn", new[] { "StaffId" });
            DropIndex("dbo.EmployeeLeaveAccount", new[] { "StaffId" });
            DropIndex("dbo.GroupAssociation", new[] { "EmployeeId" });
            DropIndex("dbo.LaterOff", new[] { "StaffId" });
            DropIndex("dbo.MaintenanceOff", new[] { "StaffId" });
            DropIndex("dbo.ManualPunch", new[] { "StaffId" });
            DropIndex("dbo.OTApplication", new[] { "StaffId" });
            DropIndex("dbo.OTApplicationEntry", new[] { "StaffId" });
            DropIndex("dbo.PermissionOff", new[] { "StaffId" });
            DropIndex("dbo.PermissionTxn", new[] { "StaffId" });
            DropIndex("dbo.PermissionTxn", new[] { "ApprovalStatusBy" });
            DropIndex("dbo.PermissionTxn", new[] { "CreatedBy" });
            DropIndex("dbo.PermissionTxn", new[] { "ModifiedBy" });
            DropIndex("dbo.RHApplication", new[] { "StaffId" });
            DropIndex("dbo.StaffOfficial", new[] { "StaffId" });
            DropIndex("dbo.StaffPersonal", new[] { "StaffId" });
            DropIndex("dbo.SwipeData", new[] { "StaffId" });
            DropIndex("dbo.TeamHierarchy", new[] { "StaffId" });
            DropIndex("dbo.TeamHierarchy", new[] { "ReportingManagerId" });
            DropIndex("dbo.ViewApproval", new[] { "ApproverID" });
            DropPrimaryKey("dbo.Staff");
            DropPrimaryKey("dbo.EmployeePhoto");
            DropPrimaryKey("dbo.StaffOfficial");
            DropPrimaryKey("dbo.StaffPersonal");
            AddColumn("dbo.AttendanceData", "IFlexiShiftTime", c => c.Int(nullable: false));
            AddColumn("dbo.AttendanceData", "IsFlexiShift", c => c.Boolean(nullable: false));
            AddColumn("dbo.EmployeeLeaveAccount", "IsProcessed", c => c.Boolean(nullable: false));
            AddColumn("dbo.Holiday", "CreatedOn", c => c.DateTime(storeType: "smalldatetime"));
            AddColumn("dbo.Holiday", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.AbsenceApproval", "ApprovedById", c => c.String(maxLength: 50));
            AlterColumn("dbo.Staff", "Id", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.StaffEducation", "StaffId", c => c.String(maxLength: 50));
            AlterColumn("dbo.StaffFamily", "StaffId", c => c.String(maxLength: 50));
            AlterColumn("dbo.LeaveApplication", "StaffId", c => c.String(maxLength: 50));
            AlterColumn("dbo.LeaveApplication", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.LeaveApplication", "ModifiedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.ApplicationApproval", "ApprovedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.ApplicationApproval", "ApprovalOwner", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.ApplicationApproval", "Approval2Owner", c => c.String(maxLength: 50));
            AlterColumn("dbo.ApplicationApproval", "Approval2By", c => c.String(maxLength: 50));
            AlterColumn("dbo.ApplicationEntry", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.AtrakUserDetails", "StaffId", c => c.String(maxLength: 50));
            AlterColumn("dbo.AttendanceControlTable", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.AttendanceData", "StaffId", c => c.String(maxLength: 50));
            AlterColumn("dbo.AttendanceData", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.BenchReportingManager", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CardBlock", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.ChangeAuditLog", "UserId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CompensatoryOff", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Department", "Name", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Designation", "Name", c => c.String(nullable: false, maxLength: 150));
            AlterColumn("dbo.RequestApplication", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.RequestApplication", "AppliedBy", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.RequestApplication", "CancelledBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.EmailSendLog", "CreatedBy", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.EmployeeGroupTxn", "StaffId", c => c.String(maxLength: 50));
            AlterColumn("dbo.EmployeeLeaveAccount", "StaffId", c => c.String(maxLength: 50));
            AlterColumn("dbo.EmployeeLeaveAccount", "TransctionBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.EmployeePhoto", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.EmployeeShiftPlan", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.GroupAssociation", "EmployeeId", c => c.String(maxLength: 50));
            AlterColumn("dbo.HolidayGroup", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.HolidayGroup", "ModifiedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.HolidayWorking", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.HolidayZone", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.HolidayZone", "ModifiedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.HolidayZoneTxn", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.HolidayZoneTxn", "ModifiedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.LateComingNew", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.LaterOff", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.LaterOffDate", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.LaterOffDate", "ModifiedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.LeaveDebits", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.LeaveGroupTxn", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.LeaveGroupTxn", "ModifiedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.MaintenanceOff", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.ManualPunch", "StaffId", c => c.String(maxLength: 50));
            AlterColumn("dbo.ManualShiftChangeGrid", "StaffId", c => c.String(maxLength: 50));
            AlterColumn("dbo.ManualShiftChangeGrid", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.OTApplication", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.OTApplication", "CreatedBy", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.OTApplication", "ModifiedBy", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.OTApplicationEntry", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.OTApplicationEntry", "CreatedBy", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.PermissionOff", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.PermissionTxn", "StaffId", c => c.String(maxLength: 50));
            AlterColumn("dbo.PermissionTxn", "ApprovalStatusBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.PermissionTxn", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.PermissionTxn", "ModifiedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.RHApplication", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.RolesAndResponsibilities", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.RolesAndResponsibilities", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.RolesAndResponsibilities", "ModifiedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.RuleGroup", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.RuleGroup", "ModifiedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Settings", "CreatedBy", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Settings", "ModifiedBy", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.ShiftChangeApplication", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.ShiftChangeApplication", "CreatedBy", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.ShiftExtensionAndDoubleShift", "StaffId", c => c.String(maxLength: 50));
            AlterColumn("dbo.ShiftParentTxn", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.ShiftParentTxn", "ModifiedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.ShiftsImportData", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.StaffOfficial", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.StaffPersonal", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.SubordinateTree", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.SwipeData", "StaffId", c => c.String(maxLength: 50));
            AlterColumn("dbo.TeamHierarchy", "StaffId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.TeamHierarchy", "ReportingManagerId", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.ViewApproval", "ApproverID", c => c.String(maxLength: 50));
            AlterColumn("dbo.Workstation", "CreatedBy", c => c.String(maxLength: 50));
            AddPrimaryKey("dbo.Staff", "Id");
            AddPrimaryKey("dbo.EmployeePhoto", "StaffId");
            AddPrimaryKey("dbo.StaffOfficial", "StaffId");
            AddPrimaryKey("dbo.StaffPersonal", "StaffId");
            CreateIndex("dbo.AbsenceApproval", "ApprovedById");
            CreateIndex("dbo.StaffEducation", "StaffId");
            CreateIndex("dbo.StaffFamily", "StaffId");
            CreateIndex("dbo.LeaveApplication", "StaffId");
            CreateIndex("dbo.LeaveApplication", "CreatedBy");
            CreateIndex("dbo.LeaveApplication", "ModifiedBy");
            CreateIndex("dbo.ApplicationEntry", "StaffId");
            CreateIndex("dbo.AttendanceData", "StaffId");
            CreateIndex("dbo.CompensatoryOff", "StaffId");
            CreateIndex("dbo.EmployeeGroupTxn", "StaffId");
            CreateIndex("dbo.EmployeeLeaveAccount", "StaffId");
            CreateIndex("dbo.GroupAssociation", "EmployeeId");
            CreateIndex("dbo.LaterOff", "StaffId");
            CreateIndex("dbo.MaintenanceOff", "StaffId");
            CreateIndex("dbo.ManualPunch", "StaffId");
            CreateIndex("dbo.OTApplication", "StaffId");
            CreateIndex("dbo.OTApplicationEntry", "StaffId");
            CreateIndex("dbo.PermissionOff", "StaffId");
            CreateIndex("dbo.PermissionTxn", "StaffId");
            CreateIndex("dbo.PermissionTxn", "ApprovalStatusBy");
            CreateIndex("dbo.PermissionTxn", "CreatedBy");
            CreateIndex("dbo.PermissionTxn", "ModifiedBy");
            CreateIndex("dbo.RHApplication", "StaffId");
            CreateIndex("dbo.StaffOfficial", "StaffId");
            CreateIndex("dbo.StaffPersonal", "StaffId");
            CreateIndex("dbo.SwipeData", "StaffId");
            CreateIndex("dbo.TeamHierarchy", "StaffId");
            CreateIndex("dbo.TeamHierarchy", "ReportingManagerId");
            CreateIndex("dbo.ViewApproval", "ApproverID");
            AddForeignKey("dbo.StaffEducation", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.StaffFamily", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.AbsenceApproval", "ApprovedById", "dbo.Staff", "Id");
            AddForeignKey("dbo.LeaveApplication", "CreatedBy", "dbo.Staff", "Id");
            AddForeignKey("dbo.LeaveApplication", "ModifiedBy", "dbo.Staff", "Id");
            AddForeignKey("dbo.LeaveApplication", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.ApplicationEntry", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.AttendanceData", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.CompensatoryOff", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.EmployeeGroupTxn", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.EmployeeLeaveAccount", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.GroupAssociation", "EmployeeId", "dbo.Staff", "Id");
            AddForeignKey("dbo.LaterOff", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.MaintenanceOff", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.ManualPunch", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.OTApplication", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.OTApplicationEntry", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.PermissionOff", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.PermissionTxn", "ApprovalStatusBy", "dbo.Staff", "Id");
            AddForeignKey("dbo.PermissionTxn", "CreatedBy", "dbo.Staff", "Id");
            AddForeignKey("dbo.PermissionTxn", "ModifiedBy", "dbo.Staff", "Id");
            AddForeignKey("dbo.PermissionTxn", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.RHApplication", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.StaffOfficial", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.StaffPersonal", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.SwipeData", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.TeamHierarchy", "ReportingManagerId", "dbo.Staff", "Id");
            AddForeignKey("dbo.TeamHierarchy", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.ViewApproval", "ApproverID", "dbo.Staff", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.ViewApproval", "ApproverID", "dbo.Staff");
            DropForeignKey("dbo.TeamHierarchy", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.TeamHierarchy", "ReportingManagerId", "dbo.Staff");
            DropForeignKey("dbo.SwipeData", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.StaffPersonal", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.StaffOfficial", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.RHApplication", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.PermissionTxn", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.PermissionTxn", "ModifiedBy", "dbo.Staff");
            DropForeignKey("dbo.PermissionTxn", "CreatedBy", "dbo.Staff");
            DropForeignKey("dbo.PermissionTxn", "ApprovalStatusBy", "dbo.Staff");
            DropForeignKey("dbo.PermissionOff", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.OTApplicationEntry", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.OTApplication", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.ManualPunch", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.MaintenanceOff", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.LaterOff", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.GroupAssociation", "EmployeeId", "dbo.Staff");
            DropForeignKey("dbo.EmployeeLeaveAccount", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.EmployeeGroupTxn", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.CompensatoryOff", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.AttendanceData", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.ApplicationEntry", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.LeaveApplication", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.LeaveApplication", "ModifiedBy", "dbo.Staff");
            DropForeignKey("dbo.LeaveApplication", "CreatedBy", "dbo.Staff");
            DropForeignKey("dbo.AbsenceApproval", "ApprovedById", "dbo.Staff");
            DropForeignKey("dbo.StaffFamily", "StaffId", "dbo.Staff");
            DropForeignKey("dbo.StaffEducation", "StaffId", "dbo.Staff");
            DropIndex("dbo.ViewApproval", new[] { "ApproverID" });
            DropIndex("dbo.TeamHierarchy", new[] { "ReportingManagerId" });
            DropIndex("dbo.TeamHierarchy", new[] { "StaffId" });
            DropIndex("dbo.SwipeData", new[] { "StaffId" });
            DropIndex("dbo.StaffPersonal", new[] { "StaffId" });
            DropIndex("dbo.StaffOfficial", new[] { "StaffId" });
            DropIndex("dbo.RHApplication", new[] { "StaffId" });
            DropIndex("dbo.PermissionTxn", new[] { "ModifiedBy" });
            DropIndex("dbo.PermissionTxn", new[] { "CreatedBy" });
            DropIndex("dbo.PermissionTxn", new[] { "ApprovalStatusBy" });
            DropIndex("dbo.PermissionTxn", new[] { "StaffId" });
            DropIndex("dbo.PermissionOff", new[] { "StaffId" });
            DropIndex("dbo.OTApplicationEntry", new[] { "StaffId" });
            DropIndex("dbo.OTApplication", new[] { "StaffId" });
            DropIndex("dbo.ManualPunch", new[] { "StaffId" });
            DropIndex("dbo.MaintenanceOff", new[] { "StaffId" });
            DropIndex("dbo.LaterOff", new[] { "StaffId" });
            DropIndex("dbo.GroupAssociation", new[] { "EmployeeId" });
            DropIndex("dbo.EmployeeLeaveAccount", new[] { "StaffId" });
            DropIndex("dbo.EmployeeGroupTxn", new[] { "StaffId" });
            DropIndex("dbo.CompensatoryOff", new[] { "StaffId" });
            DropIndex("dbo.AttendanceData", new[] { "StaffId" });
            DropIndex("dbo.ApplicationEntry", new[] { "StaffId" });
            DropIndex("dbo.LeaveApplication", new[] { "ModifiedBy" });
            DropIndex("dbo.LeaveApplication", new[] { "CreatedBy" });
            DropIndex("dbo.LeaveApplication", new[] { "StaffId" });
            DropIndex("dbo.StaffFamily", new[] { "StaffId" });
            DropIndex("dbo.StaffEducation", new[] { "StaffId" });
            DropIndex("dbo.AbsenceApproval", new[] { "ApprovedById" });
            DropPrimaryKey("dbo.StaffPersonal");
            DropPrimaryKey("dbo.StaffOfficial");
            DropPrimaryKey("dbo.EmployeePhoto");
            DropPrimaryKey("dbo.Staff");
            AlterColumn("dbo.Workstation", "CreatedBy", c => c.String());
            AlterColumn("dbo.ViewApproval", "ApproverID", c => c.String(maxLength: 20));
            AlterColumn("dbo.TeamHierarchy", "ReportingManagerId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.TeamHierarchy", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.SwipeData", "StaffId", c => c.String(maxLength: 20));
            AlterColumn("dbo.SubordinateTree", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.StaffPersonal", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.StaffOfficial", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.ShiftsImportData", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.ShiftParentTxn", "ModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.ShiftParentTxn", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.ShiftExtensionAndDoubleShift", "StaffId", c => c.String(maxLength: 30));
            AlterColumn("dbo.ShiftChangeApplication", "CreatedBy", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.ShiftChangeApplication", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Settings", "ModifiedBy", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Settings", "CreatedBy", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.RuleGroup", "ModifiedBy", c => c.String());
            AlterColumn("dbo.RuleGroup", "CreatedBy", c => c.String());
            AlterColumn("dbo.RolesAndResponsibilities", "ModifiedBy", c => c.String());
            AlterColumn("dbo.RolesAndResponsibilities", "CreatedBy", c => c.String());
            AlterColumn("dbo.RolesAndResponsibilities", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.RHApplication", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.PermissionTxn", "ModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.PermissionTxn", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.PermissionTxn", "ApprovalStatusBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.PermissionTxn", "StaffId", c => c.String(maxLength: 20));
            AlterColumn("dbo.PermissionOff", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.OTApplicationEntry", "CreatedBy", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.OTApplicationEntry", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.OTApplication", "ModifiedBy", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.OTApplication", "CreatedBy", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.OTApplication", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.ManualShiftChangeGrid", "CreatedBy", c => c.String());
            AlterColumn("dbo.ManualShiftChangeGrid", "StaffId", c => c.String());
            AlterColumn("dbo.ManualPunch", "StaffId", c => c.String(maxLength: 20));
            AlterColumn("dbo.MaintenanceOff", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.LeaveGroupTxn", "ModifiedBy", c => c.String());
            AlterColumn("dbo.LeaveGroupTxn", "CreatedBy", c => c.String());
            AlterColumn("dbo.LeaveDebits", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.LaterOffDate", "ModifiedBy", c => c.String());
            AlterColumn("dbo.LaterOffDate", "CreatedBy", c => c.String());
            AlterColumn("dbo.LaterOff", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.LateComingNew", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.HolidayZoneTxn", "ModifiedBy", c => c.String());
            AlterColumn("dbo.HolidayZoneTxn", "CreatedBy", c => c.String());
            AlterColumn("dbo.HolidayZone", "ModifiedBy", c => c.String());
            AlterColumn("dbo.HolidayZone", "CreatedBy", c => c.String());
            AlterColumn("dbo.HolidayWorking", "CreatedBy", c => c.String());
            AlterColumn("dbo.HolidayGroup", "ModifiedBy", c => c.String());
            AlterColumn("dbo.HolidayGroup", "CreatedBy", c => c.String());
            AlterColumn("dbo.GroupAssociation", "EmployeeId", c => c.String(maxLength: 20));
            AlterColumn("dbo.EmployeeShiftPlan", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.EmployeePhoto", "StaffId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.EmployeeLeaveAccount", "TransctionBy", c => c.String(maxLength: 10));
            AlterColumn("dbo.EmployeeLeaveAccount", "StaffId", c => c.String(maxLength: 20));
            AlterColumn("dbo.EmployeeGroupTxn", "StaffId", c => c.String(maxLength: 20));
            AlterColumn("dbo.EmailSendLog", "CreatedBy", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.RequestApplication", "CancelledBy", c => c.String(maxLength: 10));
            AlterColumn("dbo.RequestApplication", "AppliedBy", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.RequestApplication", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Designation", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Department", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CompensatoryOff", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.ChangeAuditLog", "UserId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.CardBlock", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.BenchReportingManager", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.AttendanceData", "CreatedBy", c => c.String());
            AlterColumn("dbo.AttendanceData", "StaffId", c => c.String(maxLength: 20));
            AlterColumn("dbo.AttendanceControlTable", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.AtrakUserDetails", "StaffId", c => c.String());
            AlterColumn("dbo.ApplicationEntry", "StaffId", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.ApplicationApproval", "Approval2By", c => c.String(maxLength: 20));
            AlterColumn("dbo.ApplicationApproval", "Approval2Owner", c => c.String(maxLength: 20));
            AlterColumn("dbo.ApplicationApproval", "ApprovalOwner", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("dbo.ApplicationApproval", "ApprovedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.LeaveApplication", "ModifiedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.LeaveApplication", "CreatedBy", c => c.String(maxLength: 20));
            AlterColumn("dbo.LeaveApplication", "StaffId", c => c.String(maxLength: 20));
            AlterColumn("dbo.StaffFamily", "StaffId", c => c.String(maxLength: 20));
            AlterColumn("dbo.StaffEducation", "StaffId", c => c.String(maxLength: 20));
            AlterColumn("dbo.Staff", "Id", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.AbsenceApproval", "ApprovedById", c => c.String(maxLength: 20));
            DropColumn("dbo.Holiday", "CreatedBy");
            DropColumn("dbo.Holiday", "CreatedOn");
            DropColumn("dbo.EmployeeLeaveAccount", "IsProcessed");
            DropColumn("dbo.AttendanceData", "IsFlexiShift");
            DropColumn("dbo.AttendanceData", "IFlexiShiftTime");
            AddPrimaryKey("dbo.StaffPersonal", "StaffId");
            AddPrimaryKey("dbo.StaffOfficial", "StaffId");
            AddPrimaryKey("dbo.EmployeePhoto", "StaffId");
            AddPrimaryKey("dbo.Staff", "Id");
            CreateIndex("dbo.ViewApproval", "ApproverID");
            CreateIndex("dbo.TeamHierarchy", "ReportingManagerId");
            CreateIndex("dbo.TeamHierarchy", "StaffId");
            CreateIndex("dbo.SwipeData", "StaffId");
            CreateIndex("dbo.StaffPersonal", "StaffId");
            CreateIndex("dbo.StaffOfficial", "StaffId");
            CreateIndex("dbo.RHApplication", "StaffId");
            CreateIndex("dbo.PermissionTxn", "ModifiedBy");
            CreateIndex("dbo.PermissionTxn", "CreatedBy");
            CreateIndex("dbo.PermissionTxn", "ApprovalStatusBy");
            CreateIndex("dbo.PermissionTxn", "StaffId");
            CreateIndex("dbo.PermissionOff", "StaffId");
            CreateIndex("dbo.OTApplicationEntry", "StaffId");
            CreateIndex("dbo.OTApplication", "StaffId");
            CreateIndex("dbo.ManualPunch", "StaffId");
            CreateIndex("dbo.MaintenanceOff", "StaffId");
            CreateIndex("dbo.LaterOff", "StaffId");
            CreateIndex("dbo.GroupAssociation", "EmployeeId");
            CreateIndex("dbo.EmployeeLeaveAccount", "StaffId");
            CreateIndex("dbo.EmployeeGroupTxn", "StaffId");
            CreateIndex("dbo.CompensatoryOff", "StaffId");
            CreateIndex("dbo.AttendanceData", "StaffId");
            CreateIndex("dbo.ApplicationEntry", "StaffId");
            CreateIndex("dbo.LeaveApplication", "ModifiedBy");
            CreateIndex("dbo.LeaveApplication", "CreatedBy");
            CreateIndex("dbo.LeaveApplication", "StaffId");
            CreateIndex("dbo.StaffFamily", "StaffId");
            CreateIndex("dbo.StaffEducation", "StaffId");
            CreateIndex("dbo.AbsenceApproval", "ApprovedById");
            AddForeignKey("dbo.ViewApproval", "ApproverID", "dbo.Staff", "Id");
            AddForeignKey("dbo.TeamHierarchy", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.TeamHierarchy", "ReportingManagerId", "dbo.Staff", "Id");
            AddForeignKey("dbo.SwipeData", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.StaffPersonal", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.StaffOfficial", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.RHApplication", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.PermissionTxn", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.PermissionTxn", "ModifiedBy", "dbo.Staff", "Id");
            AddForeignKey("dbo.PermissionTxn", "CreatedBy", "dbo.Staff", "Id");
            AddForeignKey("dbo.PermissionTxn", "ApprovalStatusBy", "dbo.Staff", "Id");
            AddForeignKey("dbo.PermissionOff", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.OTApplicationEntry", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.OTApplication", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.ManualPunch", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.MaintenanceOff", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.LaterOff", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.GroupAssociation", "EmployeeId", "dbo.Staff", "Id");
            AddForeignKey("dbo.EmployeeLeaveAccount", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.EmployeeGroupTxn", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.CompensatoryOff", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.AttendanceData", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.ApplicationEntry", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.LeaveApplication", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.LeaveApplication", "ModifiedBy", "dbo.Staff", "Id");
            AddForeignKey("dbo.LeaveApplication", "CreatedBy", "dbo.Staff", "Id");
            AddForeignKey("dbo.AbsenceApproval", "ApprovedById", "dbo.Staff", "Id");
            AddForeignKey("dbo.StaffFamily", "StaffId", "dbo.Staff", "Id");
            AddForeignKey("dbo.StaffEducation", "StaffId", "dbo.Staff", "Id");
        }
    }
}
