// <auto-generated />
namespace Attendance.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedColumnLateAndEarlyConfirmationOnStaffOfficial06082021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedColumnLateAndEarlyConfirmationOnStaffOfficial06082021));
        
        string IMigrationMetadata.Id
        {
            get { return "202108060924475_AddedColumnLateAndEarlyConfirmationOnStaffOfficial#06082021"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
