// <auto-generated />
namespace Attendance.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Increased_Column_Size_AttStatus_inAttendanceData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Increased_Column_Size_AttStatus_inAttendanceData));
        
        string IMigrationMetadata.Id
        {
            get { return "202110300706227_Increased_Column_Size_AttStatus_inAttendanceData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
